version: "3.8"

services:

  configserver:
    image: hemkant/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - hemkant
      
  eurekaserver:
    image: hemkant/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
     - hemkant
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
      
  accounts:
    image: hemkant/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - hemkant
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8070/eureka/

  
  loans:
    image: hemkant/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - hemkant
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8070/eureka/

    
  cards:
    image: hemkant/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - hemkant
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 120s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8070/eureka/


networks:
  hemkant: